export const appConfiguration = {
  head: {
    viewport: 'minimum-scale=1, initial-scale=1, width=device-width',
    htmlAttrs: {
      lang: process.env.DEFAULTLANGUAGE ?? 'en',
    },
    meta: [
      { name: 'shop-name', content: process.env.STORENAME || 'PLENTYSYSTEMS AG' },
      { name: 'description', content: process.env.METADESC || 'Demo shop for plentyShop PWA' },
      { name: 'keywords', content: process.env.METAKEYWORDS || 'PlentyONE, plentyshop, pwa' },
      { name: 'theme-color', content: '#0C7992' },
      { property: 'og:title', content: process.env.OGTITLE || 'plentyShop PWA Demo' },
      { property: 'og:type', content: 'website' },
      { property: 'og:image', content: process.env.OGIMAGE || '' },
      { property: 'og:url', content: process.env.API_ENDPOINT },
    ],
    link: [
      { rel: 'icon', href: '/favicon.ico' },
      { rel: 'apple-touch-icon', href: '/favicon.ico' },
      { rel: 'preload', href: '/favicon.ico' },
      { rel: 'preconnect', href: 'https://challenges.cloudflare.com/turnstile/v0/b/b0e4a89976ce/api.js' },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/154/full/gear-drone-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/162/full/wear-bag-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/163/full/wear-bag-02.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/157/full/gear-headphones-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/156/full/gear-smartphone-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/155/full/gear-headphones-02.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/169/full/wear-sneaker-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/158/full/gear-speaker-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/159/full/gear-vacuum-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/168/full/wear-slippers-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/161/full/gear-smartwatch-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/164/full/wear-bag-03.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/167/full/wear-shirt-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/160/full/gear-vrset-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/mevofvd5omld/frontend/Test_Banner_Drone/drone-A-1024.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/mevofvd5omld/frontend/Test_Banner_Person/guy-1024.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/mevofvd5omld/frontend/headphones-mediacard.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/mevofvd5omld/frontend/Test_Banner_Person/guy-768.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/mevofvd5omld/frontend/Test_Banner_Drone/drone-A-768.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/158/middle/gear-speaker-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/166/middle/wear-cap-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/164/middle/wear-bag-03.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/161/middle/gear-smartwatch-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/169/middle/wear-sneaker-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/160/middle/gear-vrset-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/154/middle/gear-drone-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/157/middle/gear-headphones-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/165/middle/wear-belt-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/168/middle/wear-slippers-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/167/middle/wear-shirt-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/156/middle/gear-smartphone-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/159/middle/gear-vacuum-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/155/middle/gear-headphones-02.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/163/middle/wear-bag-02.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/162/middle/wear-bag-01.png" },
      { rel: 'preconnect', href: "https://plentyshop.plentymarkets.com/_ipx/s_300x80/images/logo.svg" },
      { rel: 'preconnect', href: "https://plentyshop.plentymarkets.com/_ipx/s_150x40/images/logo.svg" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/mevofvd5omld/frontend/Test_Banner_Person/guy-320.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/mevofvd5omld/frontend/Test_Banner_Drone/drone-A-320.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/167/secondPreview/wear-shirt-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/164/secondPreview/wear-bag-03.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/155/secondPreview/gear-headphones-02.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/161/secondPreview/gear-smartwatch-01.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/155/secondPreview/gear-headphones-02.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/160/secondPreview/gear-vrset-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/161/secondPreview/gear-smartwatch-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/166/secondPreview/wear-cap-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/165/secondPreview/wear-belt-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/154/secondPreview/gear-drone-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/157/secondPreview/gear-headphones-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/159/secondPreview/gear-vacuum-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/154/secondPreview/gear-drone-01.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/162/secondPreview/wear-bag-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/169/secondPreview/wear-sneaker-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/158/secondPreview/gear-speaker-01.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/160/secondPreview/gear-vrset-01.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/157/secondPreview/gear-headphones-01.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/164/secondPreview/wear-bag-03.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/165/secondPreview/wear-belt-01.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/163/secondPreview/wear-bag-02.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/159/secondPreview/gear-vacuum-01.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/168/secondPreview/wear-slippers-01.png.avif" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/158/secondPreview/gear-speaker-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/163/secondPreview/wear-bag-02.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/160/preview/gear-vrset-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/159/preview/gear-vacuum-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/164/preview/wear-bag-03.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/155/preview/gear-headphones-02.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/157/preview/gear-headphones-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/165/preview/wear-belt-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/156/preview/gear-smartphone-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/163/preview/wear-bag-02.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/169/preview/wear-sneaker-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/162/preview/wear-bag-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/154/preview/gear-drone-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/158/preview/gear-speaker-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/167/preview/wear-shirt-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/161/preview/gear-smartwatch-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/168/preview/wear-slippers-01.png" },
      { rel: 'preconnect', href: "https://cdn02.plentymarkets.com/v5vzmmmcb10k/item/images/166/preview/wear-cap-01.png" }
    ],
    title: process.env.STORENAME || 'plentyShop PWA',
  },
};
